version: '2'
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_patterns:
      - '**/*.test.js'
      - '**/*.test.jsx'
      - '**/*.stories.jsx'

exclude_patterns:
  - 'packages/utilities/psammead-locales/moment/*.test.js'
  - '**/examples/**'
