// source: https://blog.udemy.com/arabic-proverbs/
const wisdomList = [
  'Give your friends your money and your blood, but don’t justify yourself. Your enemies won’t believe it and your friends won’t need it.',
  'Unity is power.',
  'Beware the levelheaded person if they’re angry.',
  'Avoid the company of liars, but if you can’t, don’t believe them.',
  'Be wary around your enemy once, and your friend a thousand times. A double crossing friend knows more about what harms you.',
  'The best answer will come from the person who is not angry.',
  'Go with the lesser of two evils.',
  'The smarter you are, the less you speak.',
  'If you’re unable to reward, then make sure to thank.',
  'Send a wise man; don’t advise him.',
  'Everyone is critical of the flaws of others, but blind to their own.',
  'Lack of intelligence is the greatest poverty.',
  'It’s better to fix what you have than wait to get what you don’t have.',
  'Be patient and you’ll get what you want.',
  'Actions speak louder than words.',
  'An envious person is the unhappiest.',
  'Good health is a crown worn by the healthy than only the ill can see.',
  'There’s always tomorrow.',
  'A tree begins with a seed.',
  'Anger begins with madness, but ends in regret.',
  'Avoid that which requires an apology.',
  'He makes a dome out of a grain.',
  'Laugh and the world laughs with you; weep, and you weep alone.',
  'You can’t clap with one hand.',
  'If the wind blows, ride it.',
  'Visit rarely, and you will be more loved.',
  'Time is made of gold.',
  'The key to everything is determination.',
  'Silence is the sign of approval.',
  'Lying is a disease, and truth is a cure.',
  'Keeping a secret is a commitment.',
  'If you have an opinion, you better be determined.',
  'A foolish man may be known by six things: Anger without cause, speech without profit, change without progress, inquiry without object, putting trust in a stranger, and mistaking foes for friends.',
  'A house divided cannot stand.',
  'Arrogance diminishes wisdom.',
  'A secret is like a dove: when it leaves my hand it takes wing.',
  'A known mistake is better than an unknown truth.',
  'A sense of humor is the pole that adds balance to our steps as we walk the tightrope of life.',
  'Ask the experienced rather than the learned.',
  'Every sun has to set.',
  'Wishing does not make a poor man rich.',
  'No crowd ever waited at the gates of patience.',
  'He who sees the calamity of other people finds his own calamity light.',
  'Do not buy either the moon or the news, for in the end they will both come out.',
  'Believe what you see and lay aside what you hear.',
  'Arrogance is a weed that grows mostly on a dunghill.',
  'Ask your purse what you should buy.',
  'The fruit of silence is tranquility.',
  'Think of the going out before you enter.',
  'The fruit of timidity is neither gain nor loss.',
  'What is learned in youth is carved in stone.',
  'Opinion comes before the bravery of the braves.',
  'The stupid might want to help you, but they just ended up hurting you.',
  'You reap what you sow.',
  'Ignorance is the most terrible acquaintance.',
  'The house of a tyrant is a ruin.',
  'If you are charitable, you are rich.',
  'Distance equals disaffection.',
  'The carpenter’s door is loose.',
  'With care do you realize your opportunities.',
  'The stingy have large porches and little morality.',
  'Close the door that brings in the wind and relax.',
  'Experimentation is the greatest science.',
  'A tree begins with a seed.',
  'Make distance between you and every dirtiness.',
  'Tomorrow is close if you have patience,',
  'Eat less to sleep more.',
  'Tougher than a stone.',
  'Forgetting is the plague of knowledge.',
  'The wisest is the one who can forgive.',
  'More skillful than a silk worm.',
  'Determination is the key to everything.',
  'You are striking cold iron.',
  'In haste there is regret, but in patience and care there is peace and safety.',
  'Days are like countries.',
  'Avoid things that will require an apology.',
  'The envious were created just to be infuriated.',
  'Do not eat your bread on somebody else’s table.',
  'Do not delay today’s work for tomorrow.',
  'Laughing without a reason is rude.',
  'Like a fish in water.',
  'Wealth comes like a turtle, and runs away like a gazelle.',
  'Planning is half of living.',
  'It’s better to avoid mistakes altogether than do something that you should apologize for after.',
  'Winds blow counter to what the ship wants.',
  'There is always something to learn from experimentation.',
  'Get together like brothers, but work together like strangers.',
  'The rope of lies is short.',
  'Falseness lasts an hour, the truth lasts until the end of time.',
];

const getRandomInteger = (min, max) =>
  Math.floor(Math.random() * (max - min)) + min;

module.exports = () => {
  const randomInt = getRandomInteger(0, wisdomList.length);

  return wisdomList[randomInt];
};
