import latinAndCyrillic from './scripts/latin-and-cyrillic';
import latinDiacritics from './scripts/latin-with-diacritics';
import arabic from './scripts/arabic';
import arabicPashto from './scripts/arabic-pashto';
import bengali from './scripts/bengali';
import burmese from './scripts/burmese';
import devanagariAndGurmukhi from './scripts/devanagari-and-gurmukhi';
import sinhalese from './scripts/sinhalese';
import tamil from './scripts/tamil';
import thai from './scripts/thai';
import noAscendersOrDescenders from './scripts/no-ascenders-or-descenders';

export { latinAndCyrillic as latin };
export { latinAndCyrillic as cyrillic };
export { latinDiacritics };
export { arabic };
export { arabicPashto };
export { bengali };
export { burmese };
export { devanagariAndGurmukhi as hindi };
export { devanagariAndGurmukhi as nepali };
export { sinhalese };
export { tamil };
export { thai };
export { noAscendersOrDescenders as chinese };
export { noAscendersOrDescenders as korean };
export { noAscendersOrDescenders as ethiopic };
